// <auto-generated />
using System;
using Entreprenly.WebServices.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entreprenly.WebServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613210906_RefineProfileColumns")]
    partial class RefineProfileColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entreprenly.WebServices.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Iam.Domain.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("MEDIUMTEXT")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("plan");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_profiles_user_id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RolesId", "UserId")
                        .HasName("p_k_role_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_role_users_user_id");

                    b.ToTable("role_users");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("Entreprenly.WebServices.Profiles.Domain.Model.ValueObjects.NotificationSettings", "NotificationSettings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<bool>("ChatbotMessages")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_chatbot_messages");

                            b1.Property<bool>("PaymentAlerts")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_payment_alerts");

                            b1.Property<bool>("StockAlerts")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_stock_alerts");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("Entreprenly.WebServices.Profiles.Domain.Model.ValueObjects.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_currency");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_language");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_theme");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_timezone");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Entreprenly.WebServices.Iam.Domain.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_users_roles_roles_id");

                    b.HasOne("Entreprenly.WebServices.Iam.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_users_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
