// <auto-generated />
using System;
using Entreprenly.WebServices.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entreprenly.WebServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615211017_AddSalesContext")]
    partial class AddSalesContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entreprenly.WebServices.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Iam.Domain.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("MEDIUMTEXT")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("plan");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_profiles_user_id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Sales.Domain.Model.Aggregates.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("owner_email");

                    b.Property<int>("SaleCount")
                        .HasColumnType("int")
                        .HasColumnName("sale_count");

                    b.Property<double>("TotalCash")
                        .HasColumnType("double")
                        .HasColumnName("total_cash");

                    b.Property<double>("TotalDigital")
                        .HasColumnType("double")
                        .HasColumnName("total_digital");

                    b.HasKey("Id")
                        .HasName("p_k_cash_registers");

                    b.HasIndex("OwnerEmail", "Date")
                        .IsUnique()
                        .HasDatabaseName("i_x_cash_registers_owner_email_date");

                    b.ToTable("cash_registers", (string)null);
                });

            modelBuilder.Entity("Entreprenly.WebServices.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("owner_email");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<double>("Total")
                        .HasColumnType("double")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("p_k_sales");

                    b.HasIndex("OwnerEmail")
                        .HasDatabaseName("i_x_sales_owner_email");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RolesId", "UserId")
                        .HasName("p_k_role_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_role_users_user_id");

                    b.ToTable("role_users");
                });

            modelBuilder.Entity("Entreprenly.WebServices.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("Entreprenly.WebServices.Profiles.Domain.Model.ValueObjects.NotificationSettings", "NotificationSettings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<bool>("ChatbotMessages")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_chatbot_messages");

                            b1.Property<bool>("PaymentAlerts")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_payment_alerts");

                            b1.Property<bool>("StockAlerts")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("notifications_stock_alerts");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("Entreprenly.WebServices.Profiles.Domain.Model.ValueObjects.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_currency");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_language");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_theme");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("preferences_timezone");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Entreprenly.WebServices.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.OwnsOne("Entreprenly.WebServices.Sales.Domain.Model.ValueObjects.PaymentReceipt", "PaymentReceipt", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .HasColumnType("int")
                                .HasColumnName("sale_id");

                            b1.Property<double>("Amount")
                                .HasColumnType("double")
                                .HasColumnName("amount");

                            b1.Property<DateTimeOffset>("ConfirmedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("confirmed_at");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("method");

                            b1.Property<string>("TransactionCode")
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("transaction_code");

                            b1.HasKey("SaleId")
                                .HasName("p_k_sale_payment_receipts");

                            b1.ToTable("sale_payment_receipts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SaleId")
                                .HasConstraintName("f_k_sale_payment_receipts_sales_sale_id");
                        });

                    b.OwnsMany("Entreprenly.WebServices.Sales.Domain.Model.ValueObjects.SaleItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint")
                                .HasColumnName("product_id");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("varchar(160)")
                                .HasColumnName("product_name");

                            b1.Property<int?>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<int>("SaleId")
                                .HasColumnType("int")
                                .HasColumnName("sale_id");

                            b1.Property<double>("Subtotal")
                                .HasColumnType("double")
                                .HasColumnName("subtotal");

                            b1.Property<double>("UnitPrice")
                                .HasColumnType("double")
                                .HasColumnName("unit_price");

                            b1.Property<double?>("WeightKg")
                                .HasColumnType("double")
                                .HasColumnName("weight_kg");

                            b1.HasKey("Id")
                                .HasName("p_k_sale_items");

                            b1.HasIndex("SaleId")
                                .HasDatabaseName("i_x_sale_items_sale_id");

                            b1.ToTable("sale_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SaleId")
                                .HasConstraintName("f_k_sale_items_sales_sale_id");
                        });

                    b.Navigation("Items");

                    b.Navigation("PaymentReceipt");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Entreprenly.WebServices.Iam.Domain.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_users_roles_roles_id");

                    b.HasOne("Entreprenly.WebServices.Iam.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_role_users_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
